### PR TITLE
Make sure libcrypto threadsafety callbacks are properly set up

### PR DESCRIPTION
**Pull request by wulczer**
Multithreaded programs using libcrypto (part of OpenSSL) need to set up
callbacks to ensure safe execution. Both Python and libpq set up those
callbacks, which might lead to a conflict.

To avoid leaving dangling function pointers when being unloaded, libpq sets up
and removes the callbacks every time a SSL connection it opened and closed. If
another Python thread is performing unrelated SSL operations (like connecting
to a HTTPS server), this might lead to deadlocks, as described in
http://www.postgresql.org/message-id/871tlzrlkq.fsf@wulczer.org

Even if the problem will be remediated in libpq, it's still useful to have it
fixed in psycopg2. The solution is to use Python's own libcrypto callbacks and
completely disable handling them in libpq.

### CODE REVIEW

**Comment by wulczer** [comment]
Here's a script to reproduce deadlock when one Python thread is doing libpq over SSL and another is doing unrelated SSL:

https://gist.github.com/wulczer/82b5b52a420ac7387694

Apart from the discussion in the linked pg-hackers thread these threads are relevant:

http://www.postgresql.org/message-id/CAHUL3dpWYFnUgdgo95OHYDQ4kugdnBKPTjq0mNbTuBhCMG4xvQ@mail.gmail.com

http://www.postgresql.org/message-id/48620925.6070806@pws.com.au

**Comment by fogzot** [comment]
Patch seems fine to me. I don't have an environment to run the tests but I'll do that and merge tomorrow unless @dvarrazzo  beats me to it. :D

**Comment by dvarrazzo** [comment]
I'm totally fine with the patch (thank you Jan!) but I prefer to apply it to my branch, where I can make the tests run, and then merge it to master.

**Comment by wulczer** [comment]
Sure thing! Feel free to close the PR and apply the patch via different means :)

**Comment by dvarrazzo** [comment]
It's fine as it is: I don't really like the way github makes the merge (with an extra commit) but it detects automatically if the changeset is pushed "manually" and closes the requests itself. We can leave everything as it is now ;-)

**Comment by wulczer** [comment]
Hi! Just checking in, where are we on this?

**Comment by dvarrazzo** [comment]
Right, I forgot to include this in the last release :\ sorry, I only got through the bug list and skipped the pull request.

I'll try to release it soon in a 2.6.1.

**Comment by wulczer** [comment]
No problem at all, I actually submitted this after 2.6 got released.

Just wanted to make sure it doesn't fall through the cracks, thanks!

**Comment by dvarrazzo** [comment]
Absolutely no, thank you: it must have been a tricky nut to crack!

**Comment by dvarrazzo** [comment]
Merged, thank you very much.

**Comment by wulczer** [comment]
Yay! Thank you!

**Comment by bhagany** [comment]
Is there any chance of getting this into a stable release soon?  We get bitten by this relatively frequently.

**Comment by dvarrazzo** [comment]
I was aiming for a release the past week but I couldn't. I'll try to have it out before Monday.

**Comment by bhagany** [comment]
Great!  Thanks very much.

**Comment by dvarrazzo** [comment]
Still have to write the release notes to -announce but 2.6.1 is already tagged on github and released on PyPI.

**Comment by bhagany** [comment]
Thanks!

**Comment by KarelJakubec** [comment]
@wulczer I was happy as fuck when I saw this issue - debugging our app for two days, strange freezes in connect, thinking I am the only one who is expereincing it. Seeking for some wrong initialization of SSL and in the end, all I needed was to update the psycopg2. :)

Thanks a lot, you just made my day.

**Comment by wulczer** [comment]
@KarelJakubec Yeah! I love the sound of bugs squashed in the morning :metal:

**Comment by danhnguyen0902** [comment]
You are my savior, @wulczer 
I have been tracking down the crashes on my server for almost a month, and I came across this issue. All I did was to update psycopg2 to the latest, and no crashes since then.

**Comment by wulczer** [comment]
Glad to help @danhnguyen0902 :)

**Pull request closed without merging**
