### PR TITLE
Add connection.quote_ident(str)

### PR DESCRIPTION
**Pull request by a1exsh**
Also use PQescapeIdentifier to quote cursor name.

See #308 and #209.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
I really, really, don't like this method to be part of the connection. I think it should be in `extension`, taking the connection as input. The cursor would also be a better place to have it. Another option would be an object internally wrapping the connection and exposing the various escape functions provided by the libpq (string, literal, identifier, bytea), and maybe a composition function similar to the postgres [format](http://www.postgresql.org/docs/9.4/static/functions-string.html#FUNCTIONS-STRING-FORMAT) function (but please, let's talk about that before you rush implementing it).

Another observation: falling back to escape_easy should *not* be supported. If the libpq doesn't offer the feature we don't want to mock it. Conversely, the escape_easy could be reimplemented to use PQescapeIdentifier so that we don't break named cursors for old clients. The function was added to PG 9.0, which is already out of support: I don't really care about people wanting to develop on new features using libpq 8.4.

**Comment by a1exsh** [comment]
Hm... OK.  Do you think it would then make sense not to remove the enclosing quotes in escape_easy and change every place where `curs->name` is used to with `"%s"` format?

Moving `quote_ident` to cursor kinda makes sense.  What about `QuotedIdentifier` I was proposing in #308 -- is this approach OK to you?

**Comment by dvarrazzo** [comment]
Do you want to remove the quotes in order to expose it to Python? In this case no: I'm ok to expose PQescapeIdentifier, not to expose our version.

The QuotedString thingy still requires passing a connection. Using it during adaptation has been proposed several times, but has always been rejected (with reasons) by @fogzot and others.

An approach I'm thinking is to add a "compose" method to the cursor to the object returning a sql statement to pass to execute:

```python
from psycopg2.extensions import Identifier

cur.execute(
    cur.compose(
        "insert into %(table)s %(field)s values (%%s)",
        dict(table=Identifier("tbl"), field=Identifier("fld"))),
    [42])
```

Rough ideas are:

* wrapper objects `Identifier`, `Literal` and maybe `String` and `Bytea` would be exposed (names to review, to avoid clashes). These objects derive from a base class e.g. `Composable`.
* `compose()` knows how to adapt `Identifier` and `Literal`. If a normal python object is passed, it is adapted as per `adapt()` and passed as string, going through the regular adaptation machinery.
* `compose()` takes a dict or a string as argument.
* `Composable` objects expose an (e.g.) `adapt()` method taking a connection or cursor and returning the adapted string. The method can be called manually and is used internally by `cur.compose()`.

All in all we have this pseudostuff:

```python
class Composable:
    def __init__(self, wrapped):
        self.wrapped = wrapped
    def adapt(self, conn_or_cur):
        raise NotImplementedError

class Identifier(Composable):
    def adapt(self, conn_or_cur):
        pgconn = get_it_from(conn_or_cur)
        return libpq.PQescapeIdentifier(pgconn, self.wrapped)

# etc for Literal, String, Bytea

class cursor:
    def compose(sql, args):
        adapted = [] # TODO: handle args dict
        for arg in args:
        if isinstance(arg, Composable):
            adapted.append(arg.adapt())
        else:
           # TODO: prepare() etc
           adapted.append(psycopg2.extensions.adapt(arg).getquoted())

        return sql % adapted

A prototype of that can be created in Python using [my terrible hack](https://gist.github.com/dvarrazzo/b7c8f050bbd39dd2c104) to access the libpq and a mixin subclass of cursor exposing `compose()`, so we can write a test suite and check if the interface makes sense at all.

**Comment by dvarrazzo** [comment]
I'm closing this pull request as what I'd like to see in psycopg is way different from this.

**Pull request closed without merging**
