### PR TITLE
Add connection.get_dsn_parameters()

### PR DESCRIPTION
**Pull request by a1exsh**

### CODE REVIEW

**Comment by fogzot** [comment]
Seems like a useful refactor. @dvarrazzo any reason to not merge this?

**Comment by dvarrazzo** [comment]
The patch itself is ok: it merges with the other features @a1exsh has being implementing (e.g. parsing the dsn in C, I seem to remember: bug #363) and haven't really had time to get through all of them. I think we should, to acknowledge his work.

**Comment by a1exsh** [comment]
@dvarrazzo that doesn't work with a closed connection though: the memory gets deallocated by `PQfinish()` which we call from `conn_close[_locked]()`.

**Comment by dvarrazzo** [comment]
Fine, in this case the guard is ok

**Comment by dvarrazzo** [comment]
Isn't this just equivalent to `parse_dsn(conn.dsn)`?

**Comment by a1exsh** [comment]
@dvarrazzo it is almost equivalent, but it will also reveal any *implicit* connection parameters such as `client_encoding` and any parameters which were passed in form of `PG*` environment variables.

For example, you might have completely empty dsn in the connection object, while still overriding the defaults with `PGHOST/PORT/USER/etc`.  This you cannot learn from examining the connection object's `dsn` property, only by querying `PGconn`.

**Pull request merged**
