### PR TITLE
feat: Add AIX support

### LINKED ISSUE #105: Connection factories override cursor_factories
Originally submitted by: Corry Haines

The cursor subclasses appear to have been coded to override the cursor_factory kwarg that can be passed to them.

If this was the intended behavior, then I guess this is not a bug, but it seems to be a very odd behavior. Because of this behavior, adding a connection factory to an existing app caused most of the cursors to break when their request for specific cursors was ignored.

So, I have patched the subclasses to allow the cursor_factory kwarg to override the connection_factory. It allows connection factories to be dropped into place without stomping all over existing code.

I have uploaded the patch to my github clone of psycopg: https://github.com/tabletcorry/psycopg2/commit/eb46f4f80794e37a16e0848273ed12a0443ca2dd

### PR DESCRIPTION
**Pull request by abmusse**
AIX has the same issue as Solaris no .timeradd or .timersub

```
ld: 0711-317 ERROR: Undefined symbol: .timeradd

ld: 0711-317 ERROR: Undefined symbol: .timersub
```
This patch was derived from solaris_support.h and solaris_support.c

Resolves #105

### CODE REVIEW

**Comment by dvarrazzo** [comment]
I assume there isn't an equivalent for AIX of appveyor/travis right?

I can't test the patch myself so please make sure you run at least a `make check` before considering it completed, thank you

**Comment by abmusse** [comment]
Here is the [test output](https://gist.github.com/abmusse/9eabf6463214b31637a3bf403250bb2b).

**Comment by dvarrazzo** [comment]
Thank you @abmusse!

Can you figure out why some tests failed? Maybe the test database has an ASCII encoding? It doesn't seem an AIX-related problem though.

**Comment by abmusse** [comment]
> Maybe the test database has an ASCII encoding? It doesn't seem an AIX-related problem though.

Yes I changed the enconding  to UTF-8.

Here is the updated [test output](https://gist.github.com/abmusse/4f72f8060baa61caa33a1b26cbf09308)

**Comment by dvarrazzo** [comment]
Cool, thank you! I'll merge and release as soon as I can (which might be a few days because I'm out of town with limited visibility)

**Pull request merged**
