### PR TITLE
packages CI: Add Python 3.11

### PR DESCRIPTION
**Pull request by EwoutH**
Add Python 3.11 to the wheel building packing CI.

Also updates the used actions to their latest versions.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Thank you, but, just to let you know, there will be no release of 3.11 package before the *official* python release.

**Comment by EwoutH** [comment]
Thanks for getting back! Python 3.11 is now in release candidate phase, which means [it’s ABI stable](https://www.python.org/downloads/release/python-3110rc1/). It’s thus recommended and even encouraged to build wheels and upload them to PyPI, for users and other projects to test. Many packages already have done so, including NumPy, Pandas and SciPy.

**Comment by MasonLyons** [comment]
Any ETA on when this will be added now 3.11 has been released.

**Comment by dvarrazzo** [comment]
Packages are building

**Comment by dvarrazzo** [comment]
Closing this MR because the relevant changes have already been done in master. Thank you :wave:

**Comment by dvarrazzo** [comment]
Note: darwin packages are not available on github yet, according to [this resources list](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) and to [this build error](https://github.com/psycopg/psycopg2/actions/runs/3320363567/jobs/5486654852).

**Comment by dvarrazzo** [comment]
Status of release in #1514

**Pull request closed without merging**
