### PR TITLE
build fix: async is now a reserved keyword with Python3.7, rename it to async_

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
Please review it carefully, it builds and installs fine now, but I didn't do any runtime test.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
...And it breaks every other Python version.

What is this for? `async_` is already an alias for `async` since psycopg 2.7.

**Comment by LocutusOfBorg** [comment]
I don't know this was the error I got, the package was not even installable with python3.7
```
Setting up python3-psycopg2 (2.7.5-1build1) ...
  File "/usr/lib/python3/dist-packages/psycopg2/tests/test_async_keyword.py", line 43
    self.conn = self.connect(async=True)
                                 ^
SyntaxError: invalid syntax

dpkg: error processing package python3-psycopg2 (--configure):
 installed python3-psycopg2 package post-installation script subprocess returned error exit status 1
```

**Comment by dvarrazzo** [comment]
That file is not imported skipped in the test for python > 3.6. Apparently that's not enough. But the support for the alias `async_` is already in place.

**Comment by dvarrazzo** [comment]
Psycopg 2.7.5 works fine on Python 3.7: tests can run with

    $ make PYTHON=/usr/local/py37/bin/python3
    $ make PYTHON=/usr/local/py37/bin/python3 check

I don't know what you are installing, it seems a `deb` package. We don't maintain those.

**Comment by LocutusOfBorg** [comment]
So, you think we can just remove test_async_keyword.py file and live happy? this is not something that I'm hitting alone #714

**Pull request closed without merging**
