### PR TITLE
Added support for preparing the encrypted password (PQencryptPasswordConn)

### PR DESCRIPTION
**Pull request by asheshv**
Adding support for preparing the encrypted password using the libpq functions - 'PQencryptPasswordConn', and 'PQencryptPassword'.

This will allow the psycopg2 application to prepare the encrypted form of Password based on the current password encryption algorithm.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Hi, thank you for this MR, I'll take a look at it.

**Comment by asheshv** [comment]
Just a gentle reminder!
In order to add complete support for PostgreSQL 10 in pgAdmin 4, we need this.

**Comment by dvarrazzo** [comment]
@asheshv the fact this MR is required for pgAdmin 4 support of PG 10 is something I'm learning just now: wouldn't be the case of being more explicit about your goals? I know pgAdmin now depends on psycopg: I'm very honoured about this and I'm happy to support the project responsibly, but I have to *know* things, in order to act.

I didn't consider merging this in a bugfix release. If you say it has some importance we can discuss about that. But please *speak*.

The ML is the most appropriate place to discuss about new features and the timeline to push them.

**Comment by asheshv** [comment]
@dvarrazzo - Totally agree with you.
It was my mistake not to inform you the reason for the MR.
I should have discussed about the feature, and intention behind this MR.

Thanks for your quick reply, and support.
I really appreciate.
Let me send a mail to ML, and discuss further about it there.

**Comment by asheshv** [comment]
@dvarrazzo - Would you please take a review, and commit this PR?

**Comment by dvarrazzo** [comment]
There are several point of my previous review that have not been addressed, but appear outdated because you moved the code into a different file.

**Comment by asheshv** [comment]
As per the feedback, you did not like the function as a  connection method. The function is a wrapper to both `PQencryptPasswordConn` and `PQencryptPassword`, so the connection is
actually an optional parameter.

Hence - I've not moved it to 'extensions' files. And, made the passing connection/cursor object optional.

You also said: "There are a few implementation changes pretty unequivocal to fix bad
behaviour in corner cases and to adopt the same coding style of the
rest of the project."

Would you please point that out instead of being too general?
Sorry - but, I am too naive for this project.

-- Thanks, Ashesh

**Comment by dvarrazzo** [comment]
> Would you please point that out?

I've added a punctual review, no?

**Comment by asheshv** [comment]
Did you mean?
> when to release this function? Should we release a psycopg 2.8 to expose that? I guess releasing in a 2.7.X release is impolite...

To be honest, I am not right person to answer that.
I would accept as per the project standard.

**Comment by dpage** [comment]
@dvarrazzo Do you have any thoughts on when this might be merged and 2.8 released? PostgreSQL 10 has been out for ~6 months now and we're still unable to support SCRAM.

Thanks!

**Comment by dvarrazzo** [comment]
Sorry if it took longer than expected to merge, but the code had several shortcomings highlighted in the merge request that hadn't been addressed.

I'll look what I'll be realistically able to merge [for 2.8](https://github.com/psycopg/psycopg2/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22psycopg+2.8%22) and try to release it in a not too distant future.

**Pull request merged**
