### PR TITLE
Feature: cursor.callproc could accept Dict for PostgreSQL 9.0+ named parameters #16

### PR DESCRIPTION
**Pull request by mrmilosz**
Continuing https://github.com/psycopg/psycopg2/pull/16 with new named branch that will be regularly rebased off psycopg/psycopg2 master branch.

### CODE REVIEW

**Comment by mrmilosz** [comment]
Addressed dvarrazzo comments from pull 16. My ref counting might be off for the res = pvals line... it's been a while.

**Comment by eptify** [comment]
@mrmilosz, @dvarrazzo What's the current status of this feature?

**Comment by mrmilosz** [comment]
Just waiting for some comments on my latest commit.

Code is feature-complete and has unit tests :)

**Comment by dvarrazzo** [comment]
Finally merged to master, to be released in 2.7.

**Pull request merged**
