### PR TITLE
Drop support for EOL Python 3.4

### LINKED ISSUE #998: Drop Python 3.4 support
Python 3.4 has reached EOL in March, 2019.
Psycopg2 should drop support for it as well.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #998

### CODE REVIEW

**Comment by hugovk** [comment]
Merge conflict resolved.

**Comment by hugovk** [comment]
Merge conflict resolved.

**Comment by dvarrazzo** [comment]
I was thinking that, yes.

I have just created a maint_2_8 branch: future 2.8.x releases will come from there, and we will not drop support for new python releases there.

If you can rebase this on master, we can merge it, then we can drop 3.5 and 2.7 in other changesets.

Documentation should be changed too: see Prerequisite section.

If I can suggest, let's first drop 3.5, which is probably only few changes similar to these, then dropping 2.7 is going to be much more of a butchering.

**Comment by dvarrazzo** [comment]
Also missing from this changeset (and future ones) an entry in the NEWS file describing the versions dropped (see e.g. what's new in 2.8)

**Comment by hugovk** [comment]
Rebased, prerequisites updated (also added 3.9) and added NEWS entry!

**Comment by jerickso** [comment]
Removing Python 2.7 and 3.4 support will also help with moving the Windows builds to use the latest versions of Postgres libpq.

Basically, the Postgres 12 and 13 build scripts included in their distribution does not support Visual Studio versions before 2013 (Python 2.7 uses 2008 and Python 3.4 uses 2010).

I'll work on a pull request against master that will drop support for Python 2.7 and 3.4 for the Windows builds and use Postgres 13.

**Comment by dvarrazzo** [comment]
I thought I had merged this already.... Sorry. Merged now, thank you very much!

**Comment by hugovk** [comment]
No problem, you're welcome!

**Pull request merged**
