### PR TITLE
Change DictRow representation to match that of dict

### PR DESCRIPTION
**Pull request by AlexCharlton**
I believe this more closely matches expectations of what the printed representation of this class should be.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
What does it look, at the moment?

**Comment by dvarrazzo** [comment]
`DictRow` is mainly a sequence, because it wants to maintain compatibility with the requirements of the DBAPI. `RealDictRow` is more dict than sequence, breaking something. So I'm kinda -0.5 about making this change...

**Comment by AlexCharlton** [comment]
I certainly appreciate that `DictRow` acts as both a sequence and like a dict, and that is obviously fine. From a user perspective, however, you probably don't use `DictCursor` unless you want the dict part of it, and I think the representation of the object should reflect that fact and make it clear it's not returning regular rows.

I do recognize that this is a subjective matter, though :)

**Comment by fogzot** [comment]
As @dvarrazzo said `DictRow` basically is a DBAPI compatible row that can *also* be accessed using column names. It makes sense to represent it as a list.

**Comment by AlexCharlton** [comment]
¯\_(ツ)_/¯ as you wish

**Pull request closed without merging**
