### PR TITLE
Show how to troubleshoot common issues

### PR DESCRIPTION
**Pull request by mtangoo**
While building the documentation I met some errors and warnings that were not documented and only found out when dug  a little bit. Am here by making them more visible to make it convenient for new users

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Were you trying to build the docs with Python 2? That's probably no more supported

**Comment by dvarrazzo** [comment]
Wouldn't it be better to make the Makefile work than to write in the readme all the possible ways it can fail?

**Comment by dvarrazzo** [comment]
...for instance, regarding the pth, maybe it's possible to add something like `-e ../setup.py` in the requirements to have it installed in development mode more robustly?

**Comment by mtangoo** [comment]
Hi @dvarrazzo, sorry for late reply. I was mostly offline

>Were you trying to build the docs with Python 2? That's probably no more supported

No! I had Python3.9 and Python 2.7 where 2.7 is the default wrecking all the havoc. I haven't looked at Python with any database save SQLite for years so I was perplexed. Then digging this is what I found.

>Wouldn't it be better to make the Makefile work than to write in the readme all the possible ways it can fail?

Two reasons (correct me if am wrong). First I assumed there are few limited way the compilation can go wrong (if someone follows instructions correctly) mostly related to Python version conflicts. Two I thought that rather than trying to support all Python versions on Make file, setting ENV for example is easier and flexible

>...for instance, regarding the pth, maybe it's possible to add something like -e ../setup.py in the requirements to have it installed in development mode more robustly?

If any of those can be resolved by updating README, then it is fine. I just didn't bother to look further into it

**Comment by dvarrazzo** [comment]
Going about to merge old requests. Building the docs is not something I would like to offer a public interface for and I don't think that confusing Python version is the only thing that can go wrong. So I prefer to avoid merging this. Thank you very much.

**Pull request closed without merging**
