### PR TITLE
mention postgresql 11 in install docs

### PR DESCRIPTION
**Pull request by wbolster**

### CODE REVIEW

**Comment by yhoiseth** [comment]
Does this mean that the current release (2.7) supports PostgreSQL 11?

**Comment by wbolster** [comment]
yes it does work

**Comment by yhoiseth** [comment]
Thanks for the quick response. Also, I realized that I could check [the continuous integration configuration](https://github.com/psycopg/psycopg2/blob/0e89b9de2ca254b11c0221727a502522ab238fa5/scripts/travis_test.sh#L70), which shows that the tests are run against PosgreSQL 11:
```bash
# Postgres built from master
if [[ -n "$TEST_FUTURE" ]]; then
    run_test 11
fi
```

**Comment by dvarrazzo** [comment]
Merged and deployed. http://initd.org/psycopg/docs/install.html#prerequisites

**Comment by wbolster** [comment]
thanks!

**Pull request merged**
